services:
  web:
    build: .
    container_name: o2switch-like
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: mariadb-o2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Bb,JBVv4t@%-
      MYSQL_DATABASE: leew5464_gite
      MYSQL_USER: leew5464_gite
      MYSQL_PASSWORD: Bb,JBVv4t@%-
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gite
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
volumes:
  db_data:
